#!/usr/bin/env pwsh
# Contract Governance extension: init-registry.ps1
# Initialize the root contracts/ microservice contract registry.
#
# Usage: init-registry.ps1 -Service <name> [-Database <name>]
param(
    [string]$Service = "",
    [string]$Database = "",
    [switch]$Help
)
$ErrorActionPreference = 'Stop'

function Show-Usage {
    @"
Usage: init-registry.ps1 -Service <service-name> [-Database <database-name>]

Initialize root contracts/ microservice contract registry.

Options:
  -Service <name>    Service name, e.g. my-service
  -Database <name>   Database name, e.g. db_myapp; inferred from service name if omitted
  -Help              Show this help
"@
}

if ($Help) { Show-Usage; exit 0 }

if (-not $Service) {
    Write-Error "ERROR: -Service is required"
    Show-Usage
    exit 1
}

if ($Service -notmatch '^[A-Za-z0-9_.\-]+$') {
    Write-Error "ERROR: Service name may only contain letters, digits, underscores, dots, and hyphens: $Service"
    exit 1
}

# --- Locate repo root --------------------------------------------------------

. "$PSScriptRoot/common-utils.ps1"

$repoRoot = Find-RepoRoot -StartDir $PSScriptRoot
if (-not $repoRoot) { $repoRoot = Get-Location }

$contractsDir = Join-Path $repoRoot "contracts"
$registryDir  = Join-Path $contractsDir "_registry"
$serviceDir   = Join-Path $contractsDir $Service
$eventsDir    = Join-Path $serviceDir "events"

# Infer database name if not provided
if (-not $Database) {
    $base = $Service -replace '-service$', ''
    $base = $base -replace '-', '_'
    $base = $base -replace '\.', '_'
    $Database = "db_$base"
}

# --- Create directories -------------------------------------------------------

foreach ($d in @($registryDir, $eventsDir)) {
    if (-not (Test-Path $d)) { New-Item -ItemType Directory -Path $d -Force | Out-Null }
}

# --- SERVICE-MAP.md -----------------------------------------------------------

$serviceMap = Join-Path $contractsDir "SERVICE-MAP.md"
if (-not (Test-Path $serviceMap)) {
    @"
# Microservice Contract Topology

> This file is the global index of all microservice contracts.
> Each service's detailed contract data is stored in ``_registry/<service>.yaml``, owned exclusively by that service.

## Service Registry Files

| Service | Registry File | Contract Directory |
|---------|--------------|-------------------|
| $Service | [``_registry/$Service.yaml``](_registry/$Service.yaml) | ``contracts/$Service/`` |

## Service Inventory

| Service | Database | Core Responsibility | Contract Status |
|---------|----------|--------------------|-----------------|
| $Service | $Database | TBD | EMPTY |

## Consumers

| Consumer | Type | Framework | Contract |
|----------|------|-----------|----------|

## Contract Change Rules

1. Each service only writes its own ``_registry/<service>.yaml`` and ``contracts/<service>/``.
2. Providers define endpoints and events in their own ``api.yaml`` or ``events/``.
3. Consumers declare expectations in their own registry's ``consumes.feign``, ``consumes.http``, or ``consumes.mq``.
4. Consumer status is restricted to ``PENDING``, ``RESOLVED``, ``MISMATCH``.
5. Cross-service direct database access is prohibited.
"@ | Set-Content -Path $serviceMap -Encoding UTF8
    Write-Host "[contract-governance] Created contracts/SERVICE-MAP.md"
} elseif (-not (Select-String -Path $serviceMap -Pattern "\|\s*$Service\s*\|" -Quiet)) {
    Write-Warning "[contract-governance] contracts/SERVICE-MAP.md already exists; please add $Service to the service tables"
}

# --- Registry YAML -----------------------------------------------------------

$registryFile = Join-Path $registryDir "$Service.yaml"
if (-not (Test-Path $registryFile)) {
    @"
# Service Registry: $Service
# This file is written by $Service's speckit-plan phase; only $Service may modify it.
# provides is auto-derived from contract_files; no manual maintenance needed.

service: $Service
database: $Database

contract_files:
  api: $Service/api.yaml
  events: []

consumes:
  feign: []
  http: []
  mq: []
"@ | Set-Content -Path $registryFile -Encoding UTF8
    Write-Host "[contract-governance] Created contracts/_registry/$Service.yaml"
} else {
    Write-Host "[contract-governance] contracts/_registry/$Service.yaml already exists, not overwritten"
}

# --- api.yaml -----------------------------------------------------------------

$apiFile = Join-Path $serviceDir "api.yaml"
if (-not (Test-Path $apiFile)) {
    @"
openapi: 3.0.3
info:
  title: $Service API Contract
  description: |
    Endpoints provided by $Service.
    Status: EMPTY - awaiting feature plan population.
  version: 0.0.0

# Contract changelog (auto-generated by diff-contract.sh, may also be maintained manually)
# Example:
# x-changelog:
#   - id: "2026-06-05-001"
#     version: "1.1.0"
#     date: "2026-06-05"
#     type: breaking          # breaking / non-breaking / deprecated
#     path: "/api/v1/users"
#     method: "GET"
#     operationId: "listUsers"
#     summary: "Response structure adds pagination fields"

paths: {}

components:
  schemas: {}
"@ | Set-Content -Path $apiFile -Encoding UTF8
    Write-Host "[contract-governance] Created contracts/$Service/api.yaml"
} else {
    Write-Host "[contract-governance] contracts/$Service/api.yaml already exists, not overwritten"
}

# --- events/ ------------------------------------------------------------------

$gitkeep = Join-Path $eventsDir ".gitkeep"
if (-not (Test-Path $gitkeep)) { New-Item -ItemType File -Path $gitkeep -Force | Out-Null }
Write-Host "[contract-governance] Prepared contracts/$Service/events/"
Write-Host "[contract-governance] Initialization complete: $Service ($Database)"
